blank_issues_enabled: false
contact_links:
  - name: AppTest.jl package support
    url: https://github.com/ocots/AppTest.jl/discussions
    about: Please ask and answer questions about AppTest.jl here.
  - name: Control-toolbox organisation support
    url: https://github.com/orgs/control-toolbox/discussions
    about: For more general questions about control-toolbox ecosystem it's here.
